### ISSUE TITLE
Feat.: different camera support

### ISSUE THREAD

**Issue by sleepy-nols** [streetcomplete/StreetMeasure#11]
Hi, I am using a Pixel 5 which has multiple camers. When using StreetMeasure the camera view is always super narrow, I wondered if StreetMeasure could be using the 0.6 camera too of if it is already using its just not displayed. Is that possible?

Summary:
- make use of broader view cameras

**Comment by westnordost** [comment]
I am not sure if ARCore supports multiple cameras. Also, I don't really see the point. Why would you need a broader view?

**Comment by sleepy-nols** [comment]
I thought this would maybe improve AR as it has more image data. The issue I have with the narrow view is that I cannot see the point where I started a measurement while moving around, this is mostly a problem when being close to the measurement. So it would be great for being able to measure from different distances.

**Comment by westnordost** [comment]
I would accept a PR that adds this feature, but I do not plan to implement it myself. I don't think at all that it would increase measuring quality, as usually the wide camera picture has lower quality if only due to it covering a wider area.
