### ISSUE TITLE
Android 11 won't install

### ISSUE THREAD

**Issue by lenando8** [streetcomplete/StreetMeasure#2]
Hello westnordost!

I own two cellphones that are operated by Android 11 and have  Open GL Version 3.2

Google won't install the app,  it says that my phones are not suitable for the app.

Could you change the manifest, so that android 11 is allowed?

**Comment by westnordost** [comment]
11 is allowed. Your device is likely not in the list of supported devices for ARCore. See https://developers.google.com/ar/devices
