### ISSUE TITLE
Material Design: Themed App Icon

### ISSUE THREAD

**Issue by sebastien46** [streetcomplete/StreetMeasure#3]
On Android 13, using themed app icons makes StreetMeasure stick out like a sore thumb compared to StreetComplete who supports it.
It would be nice if there could be an option to enable a themed app icon to remedy this.
I am sorry I cannot provide a pull request, for I have no coding skills.
here is the documentation on how to do it nonetheless:
[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive](url)

**Comment by westnordost** [comment]
You mean the monochrome icon, right?

**Comment by sebastien46** [comment]
That is indeed what I'm talking about.

**Comment by westnordost** [comment]
The problem is that the current icon doesn't really work well in monochrome. It'd need to be changed. Just the ruler perhaps, rotated in the same way as the road in the background?

![app_icon_monochrome](https://github.com/streetcomplete/StreetMeasure/assets/4661658/797a7a2d-5449-4450-ac06-0be7aea65905)

**Comment by sebastien46** [comment]
It might just work, but additionnal testing needs to be made to ensure that the icon is visible no matter what the user-defined theme is.

**Comment by westnordost** [comment]
![image](https://github.com/streetcomplete/StreetMeasure/assets/4661658/d4afb63c-08a5-4777-8288-f8a461f1b69c)

Or like this, it's closer to the normal variant. It looks worse, but what can you do with monochrome...

**Comment by sebastien46** [comment]
Thank you for being so swift with this issue 👍
