### ISSUE TITLE
Not compatible...

### ISSUE THREAD

**Issue by Tobida** [streetcomplete/StreetMeasure#4]
Hey, 
I would Like to usw street measure for street complete. Street complete works fine at Shiftphone 6 mq with Android 10. 
Trying to Install streetmeasure leads to a Error in Playstore -my device ist "Not compatible". Any ideas how to solve this?

Thanks

**Comment by westnordost** [comment]
The app requires ARCore (aka Google Play Services for AR), ARCore only supports a very limited number of devices.

https://developers.google.com/ar/devices#google_play_devices
