### ISSUE TITLE
How to measure multiple points distance?

### ISSUE THREAD

**Issue by dpnkrg** [streetcomplete/StreetMeasure#5]
Hi @westnordost, 

How can I measure multiple points distance in one frame. 
As of now App is supporting only single direction distance. 

My requirement is like, I am having four points AB, BC, CD, DA. I want to measure distance between all of them. 

Could you please help me to achieve that . 

Thanks

**Comment by westnordost** [comment]
It is not possible with this app to measure multiple points distance.

**Comment by dpnkrg** [comment]
Hi @westnordost, 

If possible, could you please help me out to find or share code. Or how to implement multiple points measurement code in this repo.

I badly needed this.
