### ISSUE TITLE
Feature Request: Screenshot incl. GPS Coordinates

### ISSUE THREAD

**Issue by vizsim** [streetcomplete/StreetMeasure#7]
Hello,
I understand that the focus of StreetMeasure is be simple and stable to use, I am not sure wether feature requests are wanted. However, I want to give it a try. 

I am using StreetMeasure in particular to measure widths of cycleway infrastructure. As cycleway infrastructure appended to highways (lane) is not a StreetComplete quest ([ #5025](https://github.com/streetcomplete/StreetComplete/issues/5025)), my workflow so far is:
- measure the width with StreetMeasure 
- take screenshots (please see picture)
- edit afterwards at home with ID Editor

Two features might be helpful for me (and others?):
- Geotagged screenshots 
- built-in picture/screenshot mode thats would allow easier documentation of measurements

![Screenshot_20240407-142221 (Klein)](https://github.com/streetcomplete/StreetMeasure/assets/16351144/02d65962-621a-42e7-92ca-fc1f98356f2b)

![Screenshot_20240407-142215 (Klein)](https://github.com/streetcomplete/StreetMeasure/assets/16351144/bf0dc00f-3ff0-4b91-9f5b-e89b3802a9c8)

**Comment by westnordost** [comment]
I think what you are looking for might be _"A simple app to create georeferenced notes"_? Check out [GeoNotes](https://f-droid.org/en/packages/de.hauke_stieler.geonotes/), it was made for that purpose and actually created by another OSM mapper I know.

After measuring the width, you can just add a new note with the width you just recorded. That should solve your use case.

Regarding attaching the GPS position to a screenshot or something, I would say that is out of scope of this app.

**Comment by westnordost** [comment]
Nice profile pic by the way, lol
